[package]
name = "routube"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
feed-rs = "2.3.1"
openssl-sys = "0.9.108"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
text-diff = "0.4.0"
